spring:
  application:
    name: master
  profiles:
#    active: dev
    active: pro
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 1
      max-file-size: 2048MB
      max-request-size: 2048MB

#logging:
#  file: C:\Users\wxm\Desktop\xs\IOT\sinsim-iot-master\iot-manage\log\sinsim_iot.log

#无作用
#log4j:
#  appender:
#    dailyFile:
#      File: C:/Users/wxm/Desktop/xs/IOT/sinsim-iot-master/iot-manage/spring_iot.log
#    config: logback-spring.xml
#  level:
#    root: info
#  level:
#    root: debug
#    com.eservie.sinsimiot.web.IotMachineController: DEBUG
#logging.level.com.eservice.api.dao.MachineOrderMapper=DEBUG


date:
  logger: 15
  image: 30

server:
  port: 9010
#  port: 9011
  servlet:
    context-path: /api

---
spring:
  profiles: dev

  datasource:
#    url: jdbc:mysql://10.250.62.230:3306/yttps_taikang?useSSL=false&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
  #  url: jdbc:mysql://localhost:3306/sinsim-iot-master?useSSL=false&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
    jdbc-url: jdbc:mysql://localhost:3306/sinsim-iot-master?useSSL=false&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
    username: root
    password: hello123!
#    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

    tomcat:
      test-on-borrow: true
      validation-query: SELECT 1
      validation-query-timeout: 1
#      售后数据库
  datasource-aftersale-mysql-1:
      jdbc-url: jdbc:mysql://localhost:3306/aftersale_db?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      username: root
      password: hello123!
      driver-class-name: com.mysql.jdbc.Driver
      tomcat:
        initSQL: SET time_zone='+00:00'
        testOnBorrow: true
        validationQuery: SELECT 1
  datasource-sinsim_db-mysql-1:
      jdbc-url: jdbc:mysql://localhost:3306/sinsim_db?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      username: root
      password: hello123!
      driver-class-name: com.mysql.jdbc.Driver
      tomcat:
        initSQL: SET time_zone='+00:00'
        testOnBorrow: true
        validationQuery: SELECT 1
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: sinsim_iot
      username: root
      password: hello123!
#      uri: mongodb://192.168.145.128:27017/test66
#          spring.data.mongodb.uri=mongodb://192.168.145.128:27017/test66
      url: mongodb://localhost
    pythonAccessMongo: C:\Users\wxm\Desktop\xs\IOT\sinsim-iot-master\iot-manage\pythonAccessMongo.py
  redis:
#    host: 10.250.62.230
    host: 127.0.0.1
    timeout: 5000ms
    port: 6379
    password: hello123!

park:
#  ip: https://10.250.62.230:9812
#  host: 10.250.62.230
  ip: http://127.0.0.1:9812
  host: 127.0.0.1
  port: 9812
  username: partner
  password: partner

path:
  logger: ./log/
  images: ./images/
  upload: ./upload/
  excel: ./excel/
  name: staffInfo.xlsx
  export: ./export/
  zip: ./zip/

url:
  excel: /excel/
  zip: /zip/

aes:
  key: Hankun2021040909
  iv: Hankun2021040910

---
spring:
  profiles: pro

  datasource:
#    jdbc-url: jdbc:mysql://8.130.50.136:3306/sinsim-iot-master?useSSL=false&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
# 下面的 iot_mysql 是只服务器的名称，在这里是docker；下面的sinsim-iot-master是数据库名称
    jdbc-url: jdbc:mysql://iot_mysql:3306/sinsim-iot-master?useSSL=false&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull

    username: root
    password: hello123!
    driver-class-name: com.mysql.cj.jdbc.Driver

    tomcat:
      test-on-borrow: true
      validation-query: SELECT 1
      validation-query-timeout: 1
#售后数据库
  datasource-aftersale-mysql-1:
    jdbc-url: jdbc:mysql://aftersale_mysql_1:3306/aftersale_db?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: hello123!
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      initSQL: SET time_zone='+08:00'
      testOnBorrow: true
      validationQuery: SELECT 1

  datasource-sinsim_db-mysql-1:
      jdbc-url: jdbc:mysql://allinone_server_process_1:3306/sinsim_db?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      username: root
      password: hello123!
      driver-class-name: com.mysql.jdbc.Driver
      tomcat:
        initSQL: SET time_zone='+00:00'
        testOnBorrow: true
        validationQuery: SELECT 1
  data:
     mongodb:
       host: 127.0.0.1
#        host: mongodb_iot
       port: 27017
       database: sinsim_iot
#          username: root
#          password: hello123!
       username: admin
       password: admin
#      uri: mongodb://test:123456@192.168.180.113:27017/test
#       uri: mongodb://admin:admin@mongodb_iot:27017/?authSource=admin
    #          spring.data.mongodb.uri=mongodb://192.168.145.128:27017/test66
#       url: mongodb://mongodb_iot
       url: mongodb://admin:admin@mongodb_iot:27017/?authSource=admin
#     pythonAccessMongo: /home/sinsim_iot/pythonAccessMongo.py
#docker对应如下路径，主机对应在/home/sinsim_iot/upload-data/
#编辑主机下的文件，即可更改docker里的文件。方便。
     pythonAccessMongo: /opt/sinsim_iot/upload-data/pythonAccessMongo.py
#  redis:
#    host: 10.250.62.230
#    timeout: 5000ms
#    port: 6379
#    password: hello123!

park:
  ip: https://10.250.62.230:9812
  host: 10.250.62.230
  port: 9812
  username: partner
  password: partner

path:
  logger: /opt/master/log/
  images: /opt/master/images/
  upload: /opt/master/upload/
  excel: /opt/master/excel/
  name: staffInfo.xlsx
  export: /opt/master/export/
  zip: /opt/master/zip/

url:
  excel: /excel/
  zip: /zip/

aes:
  key: Hankun2021040909
  iv: Hankun2021040910
